apiVersion: v1
kind: Service
metadata:
  name: stat-processing
  labels:
    app: stat-processing
spec:
  ports:
    - name: grpc
      port: 50061
      targetPort: 50061
    - name: fileservice
      port: 50071
      targetPort: 50071
  selector:
    app: stat-processing
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stat-processing
  labels:
    app: stat-processing
spec:
  selector:
    matchLabels:
      app: stat-processing
  replicas: 2
  template:
    metadata:
      labels:
        app: stat-processing
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5001"
        prometheus.io/path: "/metrics"
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: stat-processing
          image: gcr.io/sandeep-sarkar/stat-processing:v1.1
          imagePullPolicy: Always
          args: []
          ports:
            - containerPort: 50061
          resources:
            requests:
              memory: 256Mi
              cpu: 500m
            limits:
              memory: 768Mi
              cpu: 1000m
          readinessProbe:
            exec:
              command:
                [
                  "/bin/grpc-health-probe",
                  "-addr=:50061",
                  "-connect-timeout=100ms",
                  "-rpc-timeout=150ms",
                ]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command:
                [
                  "/bin/grpc-health-probe",
                  "-addr=:50061",
                  "-connect-timeout=100ms",
                  "-rpc-timeout=150ms",
                ]
            initialDelaySeconds: 10